# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.clippy]
workspace = false
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--examples", "--tests", "--benches", "--bins"]

[tasks.format]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.format-check]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--check",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.test]
workspace = false
command = "cargo"
args = ["nextest", "run", "--all-features"]

[tasks.test-coverage]
workspace = false
description = "Generate test coverage report using cargo-llvm-cov"
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--all-features", "--workspace", "--html"]

[tasks.test-coverage-summary]
workspace = false
description = "Show test coverage summary in terminal"
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--all-features", "--workspace"]
